[deploy]
bucket = 'cfn-artifacts-cruddur-pratiksinha'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://pratiksinha.link'
EnvBackendUrl = 'https://api.pratiksinha.link'